name: C:\Anaconda3\envs\python34
dependencies:
- alabaster=0.7.6=py34_0
- babel=2.1.1=py34_0
- backports_abc=0.4=py34_0
- colorama=0.3.3=py34_0
- cycler=0.9.0=py34_0
- decorator=4.0.4=py34_0
- docutils=0.12=py34_1
- icu=54.1=0
- ipykernel=4.1.1=py34_0
- ipython=4.0.1=py34_0
- ipython-notebook=4.0.4=py34_3
- ipython-qtconsole=4.0.1=py34_4
- ipython_genutils=0.1.0=py34_0
- jedi=0.9.0=py34_0
- jinja2=2.8=py34_0
- jpeg=8d=vc10_0
- jsonschema=2.4.0=py34_0
- jupyter_client=4.1.1=py34_0
- jupyter_core=4.0.6=py34_0
- libpng=1.6.17=vc10_1
- libsodium=1.0.3=0
- libtiff=4.0.6=vc10_1
- markupsafe=0.23=py34_0
- matplotlib=1.5.0=np110py34_0
- mistune=0.7.1=py34_0
- msvc_runtime=1.0.1=vc10_0
- nbconvert=4.0.0=py34_0
- nbformat=4.0.1=py34_0
- notebook=4.0.6=py34_0
- numpy=1.10.1=py34_0
- openssl=1.0.2d=vc10_0
- pandas=0.17.1=np110py34_0
- path.py=8.1.2=py34_1
- pep8=1.6.2=py34_0
- pickleshare=0.5=py34_0
- pip=7.1.2=py34_0
- psutil=3.3.0=py34_0
- pyflakes=1.0.0=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_4
- pyqt5=5.3.2=py34_0
- pyreadline=2.1=py34_0
- python=3.4.3=5
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- pyzmq=14.7.0=py34_1
- qt=4.8.7=vc10_5
- qt5=5.4.0=0
- qtconsole=4.1.1=py34_0
- rope=0.9.4=py34_1
- scipy=0.16.0=np110py34_0
- setuptools=18.5=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_2
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- spyder=2.3.8=py34_0
- spyder-app=2.3.8=py34_0
- tk=8.5.18=vc10_0
- tornado=4.3=py34_0
- traitlets=4.0.0=py34_0
- wheel=0.26.0=py34_1
- zeromq=4.1.3=vc10_1
- zlib=1.2.8=vc10_2
- pip:
  - backports-abc==0.4
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - pyqtgraph==0.9.10
  - rope-py3k-0.9.4==1
  - sphinx-rtd-theme==0.1.7
  - tmm==0.1.4

