# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(0, 2, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.NonGraph = QtWidgets.QGridLayout()
        self.NonGraph.setObjectName("NonGraph")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_Library = QtWidgets.QTabWidget(self.frame)
        self.tab_Library.setObjectName("tab_Library")
        self.Dielectric = QtWidgets.QWidget()
        self.Dielectric.setObjectName("Dielectric")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Dielectric)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lwDielectric = QtWidgets.QListWidget(self.Dielectric)
        self.lwDielectric.setObjectName("lwDielectric")
        self.verticalLayout_3.addWidget(self.lwDielectric)
        self.tab_Library.addTab(self.Dielectric, "")
        self.Metal = QtWidgets.QWidget()
        self.Metal.setObjectName("Metal")
        self.lwMetal = QtWidgets.QListWidget(self.Metal)
        self.lwMetal.setGeometry(QtCore.QRect(10, 10, 256, 359))
        self.lwMetal.setObjectName("lwMetal")
        self.tab_Library.addTab(self.Metal, "")
        self.Semiconductor = QtWidgets.QWidget()
        self.Semiconductor.setObjectName("Semiconductor")
        self.lWSemiconductors = QtWidgets.QListWidget(self.Semiconductor)
        self.lWSemiconductors.setGeometry(QtCore.QRect(10, 10, 256, 359))
        self.lWSemiconductors.setObjectName("lWSemiconductors")
        self.tab_Library.addTab(self.Semiconductor, "")
        self.Other = QtWidgets.QWidget()
        self.Other.setObjectName("Other")
        self.lwOther = QtWidgets.QListWidget(self.Other)
        self.lwOther.setGeometry(QtCore.QRect(10, 10, 256, 359))
        self.lwOther.setObjectName("lwOther")
        self.tab_Library.addTab(self.Other, "")
        self.verticalLayout_2.addWidget(self.tab_Library)
        self.NonGraph.addWidget(self.frame, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.NonGraph, 1, 0, 1, 1)
        self.GraphFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphFrame.sizePolicy().hasHeightForWidth())
        self.GraphFrame.setSizePolicy(sizePolicy)
        self.GraphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GraphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GraphFrame.setObjectName("GraphFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GraphFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.GraphFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout.addWidget(self.GraphFrame, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnAddLayer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddLayer.sizePolicy().hasHeightForWidth())
        self.btnAddLayer.setSizePolicy(sizePolicy)
        self.btnAddLayer.setObjectName("btnAddLayer")
        self.gridLayout_4.addWidget(self.btnAddLayer, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 0, 1, 1)
        self.le_Theta0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Theta0.sizePolicy().hasHeightForWidth())
        self.le_Theta0.setSizePolicy(sizePolicy)
        self.le_Theta0.setObjectName("le_Theta0")
        self.gridLayout_4.addWidget(self.le_Theta0, 5, 0, 1, 1)
        self.btnPlot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlot.sizePolicy().hasHeightForWidth())
        self.btnPlot.setSizePolicy(sizePolicy)
        self.btnPlot.setObjectName("btnPlot")
        self.gridLayout_4.addWidget(self.btnPlot, 3, 0, 1, 1)
        self.btnRemoveLayer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveLayer.sizePolicy().hasHeightForWidth())
        self.btnRemoveLayer.setSizePolicy(sizePolicy)
        self.btnRemoveLayer.setObjectName("btnRemoveLayer")
        self.gridLayout_4.addWidget(self.btnRemoveLayer, 1, 0, 1, 1)
        self.btnSwapLayer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSwapLayer.sizePolicy().hasHeightForWidth())
        self.btnSwapLayer.setSizePolicy(sizePolicy)
        self.btnSwapLayer.setObjectName("btnSwapLayer")
        self.gridLayout_4.addWidget(self.btnSwapLayer, 2, 0, 1, 1)
        self.btnFit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFit.sizePolicy().hasHeightForWidth())
        self.btnFit.setSizePolicy(sizePolicy)
        self.btnFit.setObjectName("btnFit")
        self.gridLayout_4.addWidget(self.btnFit, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_Library.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Substrate"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Layer"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Film"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Thickness"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "TCO"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tab_Library.setTabText(self.tab_Library.indexOf(self.Dielectric), _translate("MainWindow", "Dielectric"))
        self.tab_Library.setTabText(self.tab_Library.indexOf(self.Metal), _translate("MainWindow", "Metal"))
        self.tab_Library.setTabText(self.tab_Library.indexOf(self.Semiconductor), _translate("MainWindow", "Semiconductor"))
        self.tab_Library.setTabText(self.tab_Library.indexOf(self.Other), _translate("MainWindow", "Other"))
        self.label_3.setText(_translate("MainWindow", "Graph"))
        self.btnAddLayer.setText(_translate("MainWindow", "Add Layer"))
        self.label_4.setText(_translate("MainWindow", "Angle of Incendence"))
        self.le_Theta0.setText(_translate("MainWindow", "0"))
        self.btnPlot.setText(_translate("MainWindow", "Plot"))
        self.btnRemoveLayer.setText(_translate("MainWindow", "Remove Layer"))
        self.btnSwapLayer.setText(_translate("MainWindow", "Swap Layer"))
        self.btnFit.setText(_translate("MainWindow", "Fit Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

